### ISSUE TITLE
Extra arguments should be passed on to dmenu

### ISSUE THREAD

**Issue by lopis** [NikitaIvanovV/dmenu-translate#2]
Just started using this and it's really lovely. I'm lauching `dmenu-translate` from my i3 config and it would be really useful if extra arguments passed to `dmenu-translate` would be passed on to `dmenu`. This would be more flexible than using the config file, as I have several variables for colors and fonts in my i3 config. An example of what I'd like to do:

```sh
# Colors
## primary
set $color1 #1F1D36
## secondary
set $color2 #3F3351
## highlight
set $color3 #864879
## text
set $color4 #E9A6A6
bindsym $mod+t exec dmenu-translate -fn "Ubuntu" -nb "$color2" -nf "$color4" -sb "$color3" -h 32
```

I might be able to open a PR if there's interest.

**Comment by NikitaIvanovV** [comment]
I'm glad you found the script useful! Done: e7897ec

**Comment by lopis** [comment]
Oh thank you so much!

**Comment by NikitaIvanovV** [comment]
I introduced a bug in the latest commit, fixed.

**Comment by NikitaIvanovV** [comment]
If everything works as expected on your machine, you are free to close the issue.

**Comment by lopis** [comment]
I had to play around with it still, because bash isn't playing nice with hex color codes. The # character seems to mess things a bit. I got it to work somehow, I'll share how next time I'm at my computer.

**Comment by NikitaIvanovV** [comment]
You can add single quotes around colors to prevent bash from trying to interpreting them, like this: `dmenu -nf '#ff0000'`.

**Comment by lopis** [comment]
That's actually not enough inside the script and i had to escape the values, like such:

```bash
bindsym $mod+t exec dmenu-translate -fn "Ubuntu" -nb "\$color2" -nf "\$color4" -sb "\$color3" -h 35
```

I think the quotes disappear when using them or something. But anyway, it works well enough :)
